function(mcufamily_to_arch mcu_family arch vendor)
    if (${mcu_family} STREQUAL "STM32F10x")
        set(${arch} "ARM" PARENT_SCOPE)
        set(${vendor} "STM32" PARENT_SCOPE)
    elseif (${mcu_family} STREQUAL "X86")
        set(${arch} "X86" PARENT_SCOPE)
    elseif (${mcu_family} STREQUAL "X86_64")
        set(${arch} "X86_64" PARENT_SCOPE)
    else ()
        message(FATAL_ERROR "Unsupported MCU: ${mcu}")
    endif ()
endfunction()