function(mcu_to_mcufamily mcu mcu_family)
    if (${mcu} STREQUAL "STM32F103C8T6")
        set(${mcu_family} "STM32F10x" PARENT_SCOPE)
    elseif (${mcu} STREQUAL "X86")
        set(${mcu_family} "X86" PARENT_SCOPE)
    elseif (${mcu} STREQUAL "X86_64")
        set(${mcu_family} "X86_64" PARENT_SCOPE)
    else ()
        message(FATAL_ERROR "Unsupported MCU: ${mcu}")
    endif ()
endfunction()